### ISSUE TITLE
Sometimes Candles not response

### ISSUE THREAD

**Issue by hermann1514** [D3M80L/hassio-mipow#2]
Hi,
i have the problem, that the candles sometime not responding. This happends when i change the Battery. Afer turn on, i can't control the Candle. After sometime i can control this over HA again.

Is there a limitation for USB LE Devices? I have 7 Candles.
Which is the best USB Bluetooth Dongle?

Any Idea?

**Comment by D3M80L** [comment]
Hi,

I have to verify that, but this may happen due to a long timeout value set in Linux which, what I understand, is 40 seconds ([see disccussion](https://stackoverflow.com/a/28397728)).
The default value cannot be changed in the bluepy library unfortunatelly - I will observe that soon on my candles and try to write a fix for that.

A similar behaviour can be observed when you disable the candle and then try to turn it on via HA. After a while in hassio logs you will see a warning, saying that it takes too long time to check the device status (default hassio status check is 30 seconds).

What I have found quickly, is that the connection operation may block other BT device communication ([see discussion](https://github.com/IanHarvey/bluepy/issues/303))

I use a dongle Ugreen US192 (BT 4.0) 2 meters away from the RPI4. I observed that Zigbee and USB SSD may have influence on the BT device.

Questions:
- what version of RPI do you use?
- what version of the mipowe integration do you use (the latest one)
- do you use the embedded BT or a dongle ?

**Comment by hermann1514** [comment]
Hi,
thanks for the Info.

I use a PI4 with an external USB Dongle Asus USB-BT400 Bluetooth®-Stick 4.0 and the latest mipowe Integration.
My Candles are BTL300_v6

All work fine, if all Candles a reached (at this Time Candles). So - if i must change the Battery, then the game to connect the candles to HA begin ;-) After some time it's working.
But if a add another candle (so that i have 6 or 7) it doesn't work.

Regards
Hermann

**Comment by D3M80L** [comment]
There is a pending PR with a fix for battery replacement.
I will merge it after a while, but need to test with few my candles.

Still the connection timeout may occur in some cases, but that is another issue.
Can't verify the connection on 6 or 7 devices, as I have only 5.
Don't know if that is a limitation of the bluetooth itself:
* https://superuser.com/questions/931188/how-many-devices-can-be-hooked-up-to-one-pc-bluetooth-adapter-at-a-time 
* https://medium.com/iotforall/6-things-you-didnt-know-about-bluetooth-3ebb50ba370e
* https://stackoverflow.com/a/39174115

**Comment by D3M80L** [comment]
Closing this issue, as the plan is to fix that and support BT stack in Home Assistant #7
